### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by jcrbsa** [SEI-TTG/aaiot-lib#1]
Hello,

The compile failed aaiot-lib project, when I use build command . See output:

> What went wrong:
> Execution failed for task ':compileJava'.
> > Could not resolve all files for configuration ':compileClasspath'.
>    > Could not find se.sics:ace:0.0.1-SNAPSHOT.
>      Searched in the following locations:
>        - file:/C:/Users/admin/.m2/repository/se/sics/ace/0.0.1-SNAPSHOT/maven-metadata.xml
>        - file:/C:/Users/admin/.m2/repository/se/sics/ace/0.0.1-SNAPSHOT/ace-0.0.1-SNAPSHOT.pom
>        - https://repo.maven.apache.org/maven2/se/sics/ace/0.0.1-SNAPSHOT/maven-metadata.xml
>        - https://repo.maven.apache.org/maven2/se/sics/ace/0.0.1-SNAPSHOT/ace-0.0.1-SNAPSHOT.pom
>      Required by:
>          project :

Before when i also compile core project occur the same problem:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:purge-local-repository (default-cli) on project ace: Failed to refresh project dependencies for: se.sics:ace:jar:0.0.1-SNAPSHOT: required artifacts missing:
> [ERROR]   xerces.wso2:xercesImpl:jar:2.8.1.wso2v2
> [ERROR]
> [ERROR] for the artifact:
> [ERROR]   se.sics:ace:jar:0.0.1-SNAPSHOT

Is build ok in this core project?

**Comment by sebastian-echeverria** [comment]
The compilation is failing because it is not finding the required library that is listed as a dependency in this repo's readme. That library, ace-java (called simply "ace" or "se.sics.ace" in the build file) has not been properly installed in your local Maven repo yet. You have to do that before this project will compile. I added some more details to the readme file on how to do this to help out.
